image: Visual Studio 2019

version: "{build}"

build: off

install: |
  choco install innosetup
  SET "PATH=C:\Program Files (x86)\Inno Setup 6;%PATH%"

test_script:
  - CALL "build.bat" Build All Release

artifacts:
  - path: setup\PerfmonBar.*.exe
    name: Installer
